name: phpcs-validate
on:
  pull_request:
jobs:
  code-standard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Composer Downloads
        uses: actions/cache@v2
        with:
          path: vendor/
          key: ${{ runner.OS }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1.6
          extensions: bcmath

      - name: Install dependencies
        env:
          COMPOSER_AUTH: '{"github-oauth":{"github.com":"${{ secrets.GITHUB_TOKEN }}"}}'
        run: composer install --prefer-dist

      - name: Running sniffer PSR12
        run: composer phpcs